### ISSUE TITLE
Add Extended Gang Wars support

### ISSUE THREAD

**Issue by BengbuGuards** [AndroidModLoader/JPatch#10]
I think .asi mod Extended Gang Wars is interesting. If JPatch(or a new .so mod)can add these function, it won't boring after all missions. Source code: [https://github.com/CookiePLMonster/ExGangWars](https://github.com/CookiePLMonster/ExGangWars)

**Comment by RusJJ** [comment]
Maybe later

**Comment by RusJJ** [comment]
I will see. Maybe it will be a different mod with appropriate credits to Silent.
