### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by BengbuGuards** [AndroidModLoader/JPatch#11]
1. Allow turn searchlights on polmav and smokes on stuntplane and cropduster.
2. Some SCM fixes, such as using rancher lure variants during Lure missions, fixing appointments with Michelle, skipping cutsences during some missions (especially Air Raid).
3. Leave the vehicle without closing the door, just like on the PC, with the joystick.
4. Switch flying mode on hydra by button.
5. Fix parachute landing animation and restore detonator using animation.
6. Add RepairGTA mod.
7. Add [0DD2FixAsm_call](https://github.com/XMDS/OP_0DD2FixAsm_call) fix.
8. From MixSets: crouch with any weapon (such as camera and grenade).

These recommendations are very important and do have practical implications.

**Comment by AndroidModLoader** [comment]
№7 is related to the CLEO itself and wont be included here.
About the others: i like to add them all, let's see in the near future

**Comment by BengbuGuards** [comment]
Another question - I noticed that the mod includes GTASAAndroid_Structs (similar to plugin-sdk), but I didn't find the repository. Maybe it's set to hidden? Could you please make it public?

Regarding №1 turn on polmav's searchlight, I've written a cleo script to enable it, but it would be better to implement it in .so. The bool `m_bSearchLightEnabled` is the CHeli offset 0xA25 found by IDA decompiling `CHeli::ProcessControl()` . about stuntplanes and cropdusters' smoke, I also found a possible offset 0xA14, but it didn't work. It should make it easier to write scripts and AML mods if these structures are made public.

**Comment by RusJJ** [comment]
Im not going to release my private reversing project as it is:
1. Affilates Rockstar EULA;
2. Protects my mod from being taken over kids from youtube pretending they are good at modding

**Comment by BengbuGuards** [comment]
I think it would be good to create private groups of modders on discord or elsewhere, to isolate the child "modders" who can't even tell the difference between cleo and asi!
These groups are very common in China and serve as a place to share coding resources.

**Comment by BengbuGuards** [comment]
Hi killman, after a good while I've implemented a cleo script to switch stunt and cropduster smoke, just need to invert the bool  `m_bSmokeEjectorEnabled` at the CPlane+0xA14 offset. The switch polmav is similar, it is CHeli+0xA25 offset, take the inverse bool `m_bSearchLightEnabled`. You can refer to these addresses to implement these functions, activated by button 7 (horn).

**Comment by RusJJ** [comment]
№1 is in researching now
№2 not now
№3 i think no, or maybe not now
№4 in researching
№5 in v1.4.3
№6 not in JPatch
№7 CLEOMod
№8 in v1.4.3

Closing it to keep it clean.
