### ISSUE TITLE
Is it somehow possible to fix sharp, wall-like draw distance cutoff due to less dense distant fog?

### ISSUE THREAD

**Issue by Username1-a** [AndroidModLoader/JPatch#12]
Hello, as you probably know, this is one of the most jarring issues of the  mobile version – this sharp, wall-like draw distance cutoff due to less dense distant fog (it's even more noticeable during the foggy weather since it greatly decreases draw distance), where as original PS2/PC versions masked that draw distance boundary much more effective with thicker fog

Would be really great if it would be possible to somehow fix this issue and bring original behavior back through JPatch in the future

Unfortunately, as workaround, when trying to increase draw distance/streaming distance a bit through libdrawdistance.so, higher values often cause flickering in a game world, especially when looking down and when falling from some high place (even at the values like 2.00)

Thank you for your work and good luck

Example screenshots:
![Screenshot_20221017-015537_GTA San Andreas](https://user-images.githubusercontent.com/47947180/233665956-b21eff1e-1298-4553-9670-f3b8b4c070b0.png)
![Screenshot_20221017-015349_GTA San Andreas](https://user-images.githubusercontent.com/47947180/233665967-d6845295-f6a9-477a-8705-4909fb803059.png)

Even more jarring example during the foggy weather without the libdrawdistance.so:
[screen-20230421.mp4.zip](https://github.com/AndroidModLoader/JPatch/files/11297231/screen-20230421.mp4.zip)

**Comment by AndroidModLoader** [comment]
As i said, everything is possible in this world. I will try few fixes i have in my mind but not now since it is not that boring. Atleast for me

**Comment by RusJJ** [comment]
Version v1.4.2.2 fixes this. Closing as completed.
