### ISSUE TITLE
CJ body doesnt update in interiors

### ISSUE THREAD

**Issue by arguits** [AndroidModLoader/JPatch#13]
Recently I was playing and I noticed that if I exercise or eat the body is not changed
I found this fix on mixmods, its a small cleo mod but for a while it causes some crashes if you can please include it with a "better" code.
https://www.mixmods.com.br/2022/07/sa-body-stats-fix-in-interiors/

**Comment by RusJJ** [comment]
The code looks fine for me. It is extremely simple tho. How often crashes appearing? Do you experience them only with the CLEO?

**Comment by arguits** [comment]
no I also use another mod that reactivates heart attack, after I removed that mod it is now working. Just a misunderstanding

**Comment by RusJJ** [comment]
Closing it as completed but i will see if i can use this. Looks interesting to me and way more logical.
