### ISSUE TITLE
Do not take weapons after being admitted to the hospital.

### ISSUE THREAD

**Issue by IcePhoenix6829** [AndroidModLoader/JPatch#16]
Starting from version 1.4, the weapon is not taken away from the main character after being admitted to the hospital. Versions 1.3 and earlier do not have this problem.

**Comment by IcePhoenix6829** [comment]
This is weird. Because in the story, I'm still in Los Santos. Maybe I'm using an outdated version AML? What apk are you using?

**Comment by RusJJ** [comment]
> This is weird. Because in the story, I'm still in Los Santos. Maybe I'm using an outdated version AML? What apk are you using?

You need the latest APK with 1.0.2.1. Probably JPatch is not started for you.

**Comment by IcePhoenix6829** [comment]
Thank you. It really helped me. I took APK from assembly ps2 to mobile + fixes. And I threw the files from my assembly where they should be. After Carl's death, the weapons disappear as they should.
