### ISSUE TITLE
Restore broken features(forgotten features) 

### ISSUE THREAD

**Issue by bloodyplayer** [AndroidModLoader/JPatch#19]
1)can we again use the countermeasures in hydra (make sure no one forgets that)
2) dodge jump and defence from melee attacks is also a very again forgotten feature this will be useful on gameplay. it can be added by placing a new button in the screen 
Usage of the button can be like holding it will make cj to defend attacks and double tapping it would trigger dodge jump in the direction according to the direction of the joystick
Pls killman bro 
Pls consider about it

**Comment by BengbuGuards** [comment]
@RusJJ The same here: https://www.youtube.com/watch?v=TTxY_S0XD8E&t=15m55s You may understand what I have said. 

In the other hand, changing some actions such as leaving the car also need fix, player will leave the car after releasing the button, but in the original version, just press the button, you'll get off the car immediately. And unless the car is on fire, CJ always close the door but the action can't be interrupted. CJ looks like a really buster lol.

In CPlane::ProcessControl(), the game used CHID::IsReleased(), if we patch it into CPad::HornJustDown() and hook that, do a special check for these vehicles, the problem will be fix properly.

**Comment by bloodyplayer** [comment]
> 

But  bro it's actually fixed by both jpatch and cheesepatch

**Comment by bloodyplayer** [comment]
@RusJJ is my idea is okey?
What do u think man?

**Comment by BengbuGuards** [comment]
> But bro it's actually fixed by both jpatch and cheesepatch

No one have fixed completely in JPatch yet, and cheesepatch's solution make many crashes and lags. You may have a look of my cleo fix, it's simply but not a good fix because it should be in JPatch by a proper solution.

**Comment by bloodyplayer** [comment]
> > But bro it's actually fixed by both jpatch and cheesepatch
> 
> No one have fixed completely in JPatch yet, and cheesepatch's solution make many crashes and lags. You may have a look of my cleo fix, it's simply but not a good fix because it should be in JPatch by a proper solution.

But bro u should talk about this to killman

**Comment by bloodyplayer** [comment]
We r waiting to see that new installments bro
