### ISSUE TITLE
A few improvements

### ISSUE THREAD

**Issue by bloodyplayer** [AndroidModLoader/JPatch#21]
1) can the airport antennas in san Andreas airports can rotate like in vice City airport 
2) animated parts in few vehicles (eg: sweeper 's brushes, phoenix hoop cap, newsvan antenna, etc...) can brought back like in silent patch for pc
3) hunter's interior is disappearing when seen thru glass it is again a old pc bug

**Comment by BengbuGuards** [comment]
Closing this issue without any reason? Almost all these functions are already included in SilentPatch, seem good.

Rotating parts are like the boats', and we need do a manual anim.

@RusJJ  And please take a look about my fixes, plane disappearing, Predator shoot btn.

**Comment by bloodyplayer** [comment]
> Closing this issue without any reason? Almost all these functions are already included in SilentPatch, seem good.
> 
> Rotating parts are like the boats', and we need do a manual anim.
> 
> @RusJJ And please take a look about my fixes, plane disappearing, Predator shoot btn.
2nd and 3rd aren't fixed yet bro
But why it closed bro

**Comment by BengbuGuards** [comment]
2nd and 3rd has fixed in PC ver in SilentPatch, they aren't not so difficult to port... Although SP isn't open source.
