### ISSUE TITLE
Exclusive cheat codes GTA SA Mobile

### ISSUE THREAD

**Issue by AndreDavis909** [AndroidModLoader/JPatch#22]
**Hello,
After installing your patch, exclusive cheat codes for the mobile version of GTA SA stopped working.**
GONPXWR — Complete invulnerability of the player and vehicle.
BIEUHQY — Weapons, tier 4 (Minigun, Vibrator, Random: Night Vision Goggles or Thermal Vision Goggles)
YACKMWS — Advance 4 hours 
BYIXZIY — Complete the current mission
KRRIHBT — Forces all controls to appear on your smartphone screen.
AFJKBNRP — Highest gambler level.
JQFUDUB — To display life, armour, and pedestrian dialogues.
**Can you find out what combination these codes changed to in your patch?**

**Comment by AndreDavis909** [comment]
Or can you fix this?

**Comment by AndreDavis909** [comment]
By default, without a patch, all cheat codes are like this: https://www.esports.net/wiki/guides/gta-san-andreas-cheat-codes-android/

**Comment by AndreDavis909** [comment]
after installing the patch, the combinations of cheat codes become the same as on the PC.

**Comment by RusJJ** [comment]
Will check **after** v1.5 release

**Comment by AndreDavis909** [comment]
Ok. I noticed that some codes may not work at all.

**Comment by RusJJ** [comment]
Are codes correct? I wrote a program, i need to rewrite all cheat hashes.
Will do ot in JPatch v1.5.1, finally figured out what was wrong

**Comment by AndreDavis909** [comment]
> Are codes correct? I wrote a program, i need to rewrite all cheat hashes. Will do ot in JPatch v1.5.1, finally figured out what was wrong
> 
> As a bonus, i will try to bring back some missing cheat codes

These? yes, the codes are correct.
GONPXWR — Complete invulnerability of the player and vehicle.
BIEUHQY — Weapons, tier 4 (Minigun, Vibrator, Random: Night Vision Goggles or Thermal Vision Goggles)
YACKMWS — Advance 4 hours
BYIXZIY — Complete the current mission
KRRIHBT — Forces all controls to appear on your smartphone screen.
AFJKBNRP — Highest gambler level.
JQFUDUB — To display life, armour, and pedestrian dialogues.

**Comment by RusJJ** [comment]
Grab the latest version of JPatch here and check cheats: https://github.com/AndroidModLoader/JPatch/actions/runs/7646773302

Crash is not happening for me after using "OHDUDE"

**Comment by AndreDavis909** [comment]
> Grab the latest version of JPatch here and check cheats: https://github.com/AndroidModLoader/JPatch/actions/runs/7646773302
> 
> Crash is not happening for me after using "OHDUDE" Current "new" cheatcodes: https://github.com/AndroidModLoader/JPatch/blob/main/GTASA_CHEATS.md

I'll test it and write to you. I see you forgot about INVINCIBILITY.
![Снимок экрана 2024-01-25 162054](https://github.com/AndroidModLoader/JPatch/assets/133629504/adc3b071-17fb-430c-913e-936e8abdd648)

**Comment by RusJJ** [comment]
Will be fixed soon, the cheat string will be the same GONPXWR

**Comment by AndreDavis909** [comment]
I collected all the codes that cause the game to crash.
BUBBLECARS
LIFESABEACH
BEKKNQV
CRAZYTOWN
HICKSVILLE
BTCDBCB
KVGYZQK
BUFFMEUP
PDNEJOH
TRUEGRIME
18HOLES
AMOMHRER
VPJTQWV
AKJJYGLC
EEGCYXT
JQNTDMH 
JUMPJET
URKQSRK
KRIJEBR

Sometimes they can cause the game to crash.
AIWPRTON
CQZIJMB
OHDUDE
AGBDLCID
NINJATOWN

These two codes may cause the game to crash after activating weapon4.
KJKSZPJ
UZUMYMW

RRRANCHER instead there is JQNTDMH, but both cause the game to crash.
SKYPREDATOR - The code is activated, but the helicopter does not spawn.

**Comment by AndreDavis909** [comment]
How's the case going?

**Comment by AndreDavis909** [comment]
Привет! можно я по русски напишу? я скачал последнее обновление jpatch: https://github.com/AndroidModLoader/JPatch/actions/runs/7725529391
После ввода чит-кода игра так же вылетает. например код на тему сутенёров и проституток BEKKNQV.

**Comment by RusJJ** [comment]
Удали все моды и клеоскрипты, кроме JPatch, введи код и дай краш-лог

**Comment by AndreDavis909** [comment]
> Удали все моды и клеоскрипты, кроме JPatch, введи код и дай краш-лог

У меня нет никаких модов и клеоскриптов, только ваш jpatch и последний apk игры с вашего поста на сайте 4pda.
Вот клаш-лог. чит-код всегда приводит к вылету игры. три раза пытался активировать чит - игра вылетает.
[aml_crashlog.txt](https://github.com/AndroidModLoader/JPatch/files/14231322/aml_crashlog.txt)

кода на изменения телосложения Си-Джея, качок BUFFMEUP, толстяк BTCDBCB, худой KVGYZQK, всегда приводят к сбою игры.
Некоторые чит-коды всегда приводят к вылету игры а некоторые коды иногда могут вызвать вылет игры, в общем не предсказуемо всё. коды на спавн транспорта иногда могут вызвать сбой игры, не предсказуемы.
По каждому чит-коду надо собрать краш-логи? если да, соберу.

**Comment by RusJJ** [comment]
Игра вылетает в процессе попытки применения текстур на полигоны (грубо говоря). Выводы сделай сам. Если не вылетало ранее, а тут стало - ну, бывает, потом гляну

**Comment by AndreDavis909** [comment]
> Игра вылетает в процессе попытки применения текстур на полигоны (грубо говоря). Выводы сделай сам. Если не вылетало ранее, а тут стало - ну, бывает, потом гляну

Ну ранее было тоже самое.
