### ISSUE TITLE
[Feature] Any solution for a working frame limiter in GTA Vice City Mobile

### ISSUE THREAD

**Issue by Username1-a** [AndroidModLoader/JPatch#23]
Hello, it's really great that you started working on JPatch for VC, too. Thank you, it's already great. It would be really neat if you could bring a working FPS limiter to GTA Vice City in future updates of JPatch (or through separate script like MoreSettings)

On the Mobile port of GTA Vice City "Frame Limiter" setting has no effect on FPS – game's still has unlocked FPS (Probably the same in GTA 3 port)

As you probably know, It causes several critical bugs making the game in it's current state and on a modern phones almost unplayable – bugs like physics issues, traffic bugs and in particular you gonna run into Unique Stunt Jump freezing bug much earlier in your savefile and it looks like there's no way to cure Android savefile, unlike PC one (at least through GTA Save'n'Play website and savefile editor for VC). It's a bug that basically permits you from 100% the game if you didn't complete all USJ early enough in your save game

More info about the bug on GTA Forums: 

https://gtaforums.com/topic/796495-iii-vc-save-file-glitch-detection-and-repair/#comment-1067503794

https://gtaforums.com/topic/98250-do-you-have-a-unique-jump-camera-problem/

Good luck to you

**Comment by RusJJ** [comment]
It's capped on 30 FPS

**Comment by RusJJ** [comment]
> Some more info about the USJ bug

That's exactly what i wanted - a detailed report about the problem. I was trying to find any info about USJ but no success. Thanks, will take a look alter!

**Comment by RusJJ** [comment]
> 1. As per GTAForums

Can you give me the link please?

**Comment by RusJJ** [comment]
Alright, replaced current framelimiter patch with a new one. Seems better but may be twitchy...
Sadly WarDrum did something with touch handling. Probably that's the main reason of removing limiter at all.

**Comment by RusJJ** [comment]
Pretty sure i won't fix the USJ glitch as it's a global timer issue

**Comment by RusJJ** [comment]
I wont fix global timer. That's all.
