### ISSUE TITLE
gta sa: game crashes when trying to enter a cheat code

### ISSUE THREAD

**Issue by Carl-Jackson24** [AndroidModLoader/JPatch#25]
Hi, I wanted to enter cheat codes and the game crashes, connected the keyboard to the phone.

**Comment by RusJJ** [comment]
Probvably I'm blind but i dont see any crashlog attached

**Comment by Carl-Jackson24** [comment]
how to make a crashlog?

**Comment by Carl-Jackson24** [comment]
> Probvably I'm blind but i dont see any crashlog attached
Also, the game crashes. entered the code KJKSZPJ or PROFESSIONALSKIT.
[aml_crashlog.txt](https://github.com/AndroidModLoader/JPatch/files/14011259/aml_crashlog.txt)

**Comment by Carl-Jackson24** [comment]
[aml_crashlog (2).txt](https://github.com/AndroidModLoader/JPatch/files/14011569/aml_crashlog.2.txt)
[aml_crashlog (3).txt](https://github.com/AndroidModLoader/JPatch/files/14011570/aml_crashlog.3.txt)

**Comment by Carl-Jackson24** [comment]
https://github.com/AndroidModLoader/JPatch/assets/157358739/eeaa85bf-b8dc-44be-bd71-52c697ae4303

**Comment by Carl-Jackson24** [comment]
> Probvably I'm blind but i dont see any crashlog attached

Have you looked at the crashlogs?

**Comment by Carl-Jackson24** [comment]
They could have closed it right away and not responded😐

**Comment by RusJJ** [comment]
Because no one loves flood
