### ISSUE TITLE
Stunt smoke?

### ISSUE THREAD

**Issue by BengbuGuards** [AndroidModLoader/JPatch#26]
I'm working on DE now, and I found that in DE Mobile, Stuntplane's smoke has been fixed. And it used `HornJustDown()` .

In SA 2.00, `HornJustDown` checks your vehicle's type and it doen't allow helicopters and planes. We can hook this thing and allows Polmav, Stuntplane and Cropduster.
Besides, `CPlane::ProcessControl` called `CHID::IsReleased` which is unavalible on touch screen. Just Redirect it to `HornJustDown`, and everything is okey.

**Comment by BengbuGuards** [comment]
Pedro Gamer's mobile fix pack includes a script named StuntSmoke, but it just re-implemented the smoking code, lol

**Comment by RusJJ** [comment]
Thanks for the info, I'll check that later
