### ISSUE TITLE
Fix the dang models disappearing when it gets close to camera

### ISSUE THREAD

**Issue by Mrhamman** [AndroidModLoader/JPatch#4]
Pls fix it's very annoying when I get haircut or in a cutscenes cus it disappears and shows the textures that are supposed to be not visible in the cutscene

**Comment by Mrhamman** [comment]
Like wtf is this
![Screenshot_20221005_121436](https://user-images.githubusercontent.com/115061059/193986381-b09efc5d-3c02-47e2-9f38-12acc899af24.jpg)

**Comment by RusJJ** [comment]
Your draw dist is too high, that's all

**Comment by Mrhamman** [comment]
That's not the issue the issue is that in cutscenes they look weird sometimes cus models gets close to camera so pls fid

**Comment by Mrhamman** [comment]
You could compare it to original and you could see what is wrong

**Comment by RusJJ** [comment]
Have you ever tried to lower "real draw dist."?

**Comment by Mrhamman** [comment]
Well then I tried but why is this fixable thing in anyways

**Comment by RusJJ** [comment]
Didn't understand
