### ISSUE TITLE
Crash with police sirens

### ISSUE THREAD

**Issue by KThuya09** [AndroidModLoader/JPatch#7]
There is a bug and It always happen when I hear police sirens

**Comment by KThuya09** [comment]
Thanks and shall I put those into game data files?

**Comment by KThuya09** [comment]
Aw ok mine is android 12 and  here is my log
[fastman92limitAdjuster.log](https://github.com/AndroidModLoader/JPatch/files/10888416/fastman92limitAdjuster.log)

**Comment by RakuTrueMod** [comment]
Yes, jpacth 1.3 error if sirine police active

**Comment by AndroidModLoader** [comment]
Fixed with JPatch v1.4
